Refactor release conflicts action to contain all logic

diff --git a/.github/actions/check-release/action.yml b/.github/actions/check-release/action.yml
--- a/.github/actions/check-release/action.yml
+++ b/.github/actions/check-release/action.yml
@@ -1,11 +1,6 @@
 name: Check release
 description: Check for conflicts in packages being released in this PR.
 
-inputs:
-  pull-request:
-    description: 'The pull request number to get changed files from.'
-    required: true
-
 runs:
   using: composite
   steps:
@@ -14,8 +9,46 @@ runs:
       with:
         fetch-depth: 0
 
+    - name: Get merge base
+      id: merge-base
+      shell: bash
+      env:
+        BASE_REF: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
+      run: |
+        echo "MERGE_BASE=$(git merge-base HEAD "refs/remotes/origin/$BASE_REF")" >> "$GITHUB_OUTPUT"
+
+    - name: Check if the commit or pull request is a release
+      id: is-release
+      uses: MetaMask/action-is-release@ebd01f8c0d1a47626e90146a7bcd99f96106949d
+      with:
+        commit-starts-with: 'Release [version],Release v[version],Release/[version],Release/v[version],Release `[version]`'
+        commit-message: ${{ github.event.pull_request.title }}
+        before: ${{ steps.merge-base.outputs.MERGE_BASE }}
+
+    - name: Get pull request number
+      id: pr-number
+      if: steps.is-release.outputs.IS_RELEASE == 'true'
+      shell: bash
+      env:
+        EVENT_NAME: ${{ github.event_name }}
+        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
+        MERGE_GROUP_HEAD_REF: ${{ github.event.merge_group.head_ref }}
+      run: |
+        if [ "$EVENT_NAME" = "pull_request" ]; then
+          echo "PR_NUMBER=$PULL_REQUEST_NUMBER" >> "$GITHUB_OUTPUT"
+        elif [ "$EVENT_NAME" = "merge_group" ]; then
+          PR_NUMBER_REGEX='/pr-([0-9]+)-'
+          if [[ "$MERGE_GROUP_HEAD_REF" =~ $PR_NUMBER_REGEX ]]; then
+            echo "PR_NUMBER=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
+          else
+            echo "::error::Could not extract PR number from merge group head ref: $MERGE_GROUP_HEAD_REF."
+            exit 1
+          fi
+        fi
+
     - name: Get target reference
       id: get-target
+      if: steps.is-release.outputs.IS_RELEASE == 'true'
       shell: bash
       env:
         EVENT_NAME: ${{ github.event_name }}
@@ -31,14 +64,16 @@ runs:
 
     - name: Check commits for changes in released packages
       id: check-release
+      if: steps.is-release.outputs.IS_RELEASE == 'true'
       shell: bash
       env:
         GH_TOKEN: ${{ github.token }}
-        PULL_REQUEST: ${{ inputs.pull-request }}
+        PULL_REQUEST: ${{ steps.pr-number.outputs.PR_NUMBER }}
         TARGET: ${{ steps.get-target.outputs.TARGET }}
       run: |
         set -euo pipefail
-        git fetch origin main
+
+        git fetch --unshallow origin main
 
         mapfile -t PACKAGES < <(find packages -maxdepth 2 -name "package.json" -not -path "*/node_modules/*")
         RELEASED_PACKAGES=()
@@ -62,7 +97,7 @@ runs:
         git fetch origin "$PULL_REQUEST_BRANCH"
 
         # Get all files changed ahead of this PR.
-        BEFORE=$(git merge-base "refs/remotes/origin/main" "origin/$PULL_REQUEST_BRANCH")
+        BEFORE=$(git merge-base "refs/remotes/origin/main" "refs/remotes/origin/$PULL_REQUEST_BRANCH")
         git diff --name-only "$BEFORE..$TARGET" > changed-files.txt
 
         CONFLICTS=()
@@ -92,35 +127,6 @@ runs:
         else
           echo "✅ No release conflicts detected."
         fi
-
-    - name: Hide previous comments
-      uses: actions/github-script@v8
-      env:
-        PR_NUMBER: ${{ inputs.pull-request }}
-      with:
-        script: |
-          const comments = await github.paginate(github.rest.issues.listComments, {
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            issue_number: process.env.PR_NUMBER,
-          });
-
-          for (const comment of comments) {
-            if (comment.body.includes('<!-- Pull request release conflict comment -->')) {
-              await github.graphql(`
-                mutation($commentId: ID!, $classifier: ReportedContentClassifiers!) {
-                  minimizeComment(input: {subjectId: $commentId, classifier: $classifier}) {
-                    minimizedComment {
-                      isMinimized
-                    }
-                  }
-                }
-              `, {
-                commentId: comment.node_id,
-                classifier: 'OUTDATED',
-              });
-            }
-          }
 
     - name: Reply on pull request
       if: steps.check-release.outputs.has-conflicts == 'true'
