Use pull request branch for determining changes, instead of base.sha

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,11 +90,31 @@ jobs:
           commit-message: ${{ github.event.pull_request.title }}
           before: ${{ steps.merge-base.outputs.MERGE_BASE }}
 
+      - name: Get pull request number
+        if: github.event_name != 'push'
+        id: pr-number
+        env:
+          EVENT_NAME: ${{ github.event_name }}
+          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
+          MERGE_GROUP_HEAD_REF: ${{ github.event.merge_group.head_ref }}
+        run: |
+          if [ "$EVENT_NAME" = "pull_request" ]; then
+            echo "PR_NUMBER=$PULL_REQUEST_NUMBER" >> "$GITHUB_OUTPUT"
+          elif [ "$EVENT_NAME" = "merge_group" ]; then
+            PR_NUMBER_REGEX='/pr-([0-9]+)-'
+            if [[ "$MERGE_GROUP_HEAD_REF" =~ $PR_NUMBER_REGEX ]]; then
+              echo "PR_NUMBER=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
+            else
+              echo "::error::Could not extract PR number from merge group head ref: $MERGE_GROUP_HEAD_REF."
+              exit 1
+            fi
+          fi
+
       - name: Check release
         if: github.event_name != 'push' && steps.is-release.outputs.IS_RELEASE == 'true'
         uses: ./.github/actions/check-release
         with:
-          before: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}
+          pull-request: ${{ steps.pr-number.outputs.PR_NUMBER }}
 
   is-release:
     name: Determine whether this is a release merge commit
